package dev.netherforge.plugin.integration

import dev.netherforge.format.bridge.BotAction
import dev.netherforge.format.bridge.BotEvent
import dev.netherforge.format.bridge.BotJoinParams
import dev.netherforge.format.bridge.BotState
import dev.netherforge.format.bridge.BotsExtension
import dev.netherforge.format.bridge.Log
import dev.netherforge.format.bridge.Problems
import dev.netherforge.format.bridge.ScriptError
import dev.netherforge.plugin.integration.support.Adapter
import dev.netherforge.plugin.integration.support.Bots
import dev.netherforge.plugin.integration.support.Editor
import dev.netherforge.plugin.integration.support.PaperServer
import dev.netherforge.plugin.integration.support.Scenario
import kotlinx.serialization.json.JsonPrimitive
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.MethodOrderer
import org.junit.jupiter.api.Order
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestInstance
import org.junit.jupiter.api.TestMethodOrder
import org.junit.jupiter.api.extension.ExtendWith
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createTempDirectory
import kotlin.io.path.readText
import kotlin.io.path.writeText
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * examples/lumen_vale, live: a fresh main world generated by its terrain and dimension type, its biomes, datapack and
 * generating shrine, and a bot playing it through: the grove's awakening, the keeper's quest, wisps, the altar and the
 * sky reach. Only on the version the example targets.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation::class)
@ExtendWith(Scenario.StopAfterFailure::class)
class LumenValeScenario {
    private val work: Path = createTempDirectory("netherforge-vale")
    private val root: Path = work.resolve("lumen_vale")
    private val server = PaperServer(onlineMode = true, maxPlayers = 2, viewDistance = 4, levelSeed = SEED, mainWorldGenerator = true)
    private lateinit var running: PaperServer.Running
    private val editor: Editor get() = running.editor
    private val bots: Bots get() = Bots(editor)
    private val log: Path get() = server.folder.resolve(LOG)

    private var shrineX = 0
    private var shrineZ = 0
    private var keeper = ""

    @BeforeAll
    fun start() {
        assumeTrue(Adapter.minecraft == "26.3", "examples/lumen_vale targets 26.3")
        for (name in listOf("lumen_vale", "vale_lore")) {
            Adapter.example.resolveSibling(name).toFile().copyRecursively(work.resolve(name).toFile())
        }
        Adapter.fixtures.resolve("lumen_vale_probe").toFile().copyRecursively(root.toFile(), overwrite = true)
        server.prepare()
        // The harness's worlds have no structures; the vale's shrine is one.
        val properties = server.folder.resolve("server.properties")
        properties.writeText(properties.readText().replace("generate-structures=false", "generate-structures=true"))
        Files.deleteIfExists(log)
        running = server.start(root, LOG)
        assertEquals(emptyList(), (editor.next { it is Problems } as Problems).problems, "the project loads clean")
    }

    @AfterAll
    fun stop() {
        try {
            if (::running.isInitialized) running.stop()
        } finally {
            work.toFile().deleteRecursively()
        }
    }

    /** Runs probe [step] and gives the fields of the line it logs. */
    private fun probe(step: String, line: String = step.substringBefore(' '), seconds: Long = 60): List<String> {
        editor.run("it-vale $step")
        val message = (editor.next(seconds) { it is Log && it.message.startsWith("$line\t") } as Log).message
        println("[vale] $message")
        return message.split('\t').drop(1)
    }

    /** Waits for [pattern] in the server's log, as the console printed it. */
    private fun printed(pattern: Regex, seconds: Long = 120): MatchResult {
        val deadline = System.nanoTime() + seconds * 1_000_000_000
        while (System.nanoTime() < deadline) {
            pattern.find(log.readText())?.let { return it }
            Thread.sleep(500)
        }
        fail("the console never printed $pattern")
    }

    private fun waitFor(seconds: Long, check: () -> Boolean): Boolean {
        val deadline = System.nanoTime() + seconds * 1_000_000_000
        while (System.nanoTime() < deadline) {
            if (check()) return true
            Thread.sleep(2000)
        }
        return false
    }

    private fun state(): BotState = bots.state(BOT)

    private fun item(name: String) = state().inventory.firstOrNull { it.name == name }

    @Test
    @Order(1)
    fun `the main world is the vale's terrain and dimension, with its three biomes, and the sky reach is made`() {
        val (name, min, max, spawn, biome) = probe("world world")
        assertEquals("world" to "-64", name to min)
        assertEquals("384", max, "the vale dimension type is 448 tall, from -64")
        println("[vale] spawn $spawn in $biome")
        assertTrue(biome in BIOMES, "the spawn is in one of the vale's biomes: $biome")
        for (it in BIOMES) {
            val found = probe("locate world $it")
            assertTrue(!found[1].startsWith("none"), "the main world has $it: $found")
        }
        val sky = probe("world sky_reach")
        assertEquals(listOf("sky_reach", "-64", "384"), sky.take(3))
        val isles = probe("locate sky_reach crystal_grove")
        assertTrue(!isles[1].startsWith("none"), "the sky reach is grove: $isles")
    }

    @Test
    @Order(2)
    fun `the ruined shrine generates in the grove and its marker becomes a keeper with a claimed chest`() {
        editor.run("locate structure lumen_vale:ruined_shrine")
        val at = printed(Regex("The nearest lumen_vale:ruined_shrine is at (?:\u001B\\[[0-9;]*m)?\\[(-?\\d+), ~, (-?\\d+)]"))
        shrineX = at.groupValues[1].toInt()
        shrineZ = at.groupValues[2].toInt()
        val column = probe("column world $shrineX $shrineZ")
        println("[vale] shrine column $column")
        assertTrue(waitFor(30) { probe("centities shrine_keeper")[1].toInt() > 0 }, "the shrine's marker spawned a keeper")
        val keepers = probe("centities shrine_keeper")
        keeper = keepers[2]
        val shrine = probe("shrine")
        println("[vale] keeper $keepers, shrine $shrine")
        assertTrue(shrine.last().endsWith("true false"), "the keeper claimed the chest, which nobody has opened: $shrine")
    }

    @Test
    @Order(3)
    fun `a bot's first steps into the grove show it the grove's awakening, which it can skip`() {
        editor.run("difficulty peaceful")
        val keeperAt = probe("centities shrine_keeper")[3].split(' ').map { it.toInt() }
        val (joined, info) = editor.request(BotsExtension.join, BotJoinParams(BOT))
        assertTrue(joined.ok, joined.error)
        bots.heard(BOT, 0, BotEvent.ResourcePack::class.java) { it.status == "successfully_loaded" }
        println("[vale] joined at ${info!!.x} ${info.y} ${info.z} in ${info.world}")
        bots.eventually(BOT) { it.onGround }
        // Into the grove, a little above the shrine's floor: falling onto it moves the bot into other blocks, which the
        // discovery module hears, and the biome there is the grove.
        val since = bots.act(BOT, BotAction.Teleport(keeperAt[0] + 1.5, keeperAt[1] + 3.0, keeperAt[2] + 0.5)).since
        bots.heard(BOT, since, BotEvent.Subtitle::class.java) { "Crystal Grove" in it.text }
        val discovered = editor.next { it is Log && it.message.startsWith("event\tlumen_vale:discovered\tcrystal_grove") }
        println("[vale] $discovered")
        bots.eventually(BOT) { it.gameMode == "spectator" }
        // The cutscene's first cue: a subtitle.
        bots.heard(BOT, since, BotEvent.Subtitle::class.java) { "The Crystal Grove" in it.text }
        println("[vale] the awakening plays: ${state().title} / ${state().subtitle}")
        bots.act(BOT, BotAction.Sneak(true))
        bots.eventually(BOT) { it.gameMode == "survival" }
        bots.act(BOT, BotAction.Sneak(false))
        assertEquals(listOf("crystal_grove"), probe("places $BOT").first().split(','))
    }

    @Test
    @Order(4)
    fun `the keeper's dialog starts the library's quest, takes shards and answers questions`() {
        val keeperAt = probe("centities shrine_keeper")[3].split(' ').map { it.toInt() }
        bots.act(BOT, BotAction.Teleport(keeperAt[0] + 1.5, keeperAt[1].toDouble(), keeperAt[2] + 0.5))
        probe("give $BOT lumen_shard 12", "gave")
        var since = bots.act(BOT, BotAction.Interact(centity = keeper, node = "robe")).since
        val first = bots.heard(BOT, since, BotEvent.Dialog::class.java).dialog
        println("[vale] keeper says ${first.body}")
        assertTrue("Shrine Keeper" in first.title, first.title)
        assertEquals(listOf("topic"), first.inputs.map { it.key })
        assertTrue(first.body.single().contains("A visitor"), "${first.body}")
        assertNotNull(item("Wanderer's Journal"), "the library hands over its journal with a first quest")

        since = bots.act(BOT, BotAction.DialogButton(button = "Offer shards")).since
        val offered = bots.heard(BOT, since, BotEvent.Dialog::class.java).dialog
        println("[vale] after the offer: ${offered.body}")
        assertEquals(listOf("active", "8", "0"), probe("quest $BOT"))

        since = bots.act(BOT, BotAction.DialogButton(button = "Ask", inputs = mapOf("topic" to JsonPrimitive("sky")))).since
        val answer = bots.heard(BOT, since, BotEvent.Dialog::class.java).dialog
        assertTrue(answer.body.single().contains("kindled lantern"), "${answer.body}")

        since = bots.act(BOT, BotAction.DialogButton(button = "My journal")).since
        val journal = bots.heard(BOT, since, BotEvent.Dialog::class.java).dialog
        println("[vale] the journal: ${journal.title} ${journal.body}")
        assertTrue(journal.body.any { "Rekindle the Vale" in it }, "${journal.body}")
        bots.act(BOT, BotAction.DialogClose)
    }

    @Test
    @Order(5)
    fun `calming three wisps completes the quest, with its lantern and the keeper's friend`() {
        repeat(3) {
            editor.run("nf spawn wisp $BOT")
            val wisp = probe("centities wisp")
            bots.eventually(BOT) { s -> s.entities.any { it.type == "minecraft:interaction" } }
            bots.act(BOT, BotAction.Interact(centity = wisp[2]))
            waitFor(10) { probe("centities wisp")[1] == "0" }
        }
        assertEquals("done", probe("quest $BOT").first())
        bots.eventually(BOT) { item("Lumen Lantern") != null && item("Wisp Essence") != null }
        val advancements = probe("advancements $BOT").first().split(',')
        println("[vale] advancements $advancements")
        assertTrue("keepers_friend" in advancements && "vale_lore:chronicle" in advancements, "$advancements")
    }

    @Test
    @Order(6)
    fun `a lamp is an altar that kindles the lantern`() {
        probe("give $BOT lumen_shard 4", "gave")
        val lamp = probe("lamp $BOT").single().split(' ').map { it.toInt() }
        var since = bots.act(BOT, BotAction.UseBlock(lamp[0], lamp[1], lamp[2], "up")).since
        bots.heard(BOT, since, BotEvent.MenuOpen::class.java) { "Lumen Altar" in it.title }
        val menu = bots.eventually(BOT) { it.menu != null }.menu!!
        assertEquals("Infuse", menu.items.single { it.slot == 22 }.name)
        val lantern = item("Lumen Lantern")!!.slot
        val screen = if (lantern < 9) 54 + lantern else 27 + lantern - 9
        bots.act(BOT, BotAction.ClickSlot(screen))
        bots.act(BOT, BotAction.ClickSlot(13))
        bots.eventually(BOT) { s -> s.menu!!.items.single { it.slot == 22 }.lore.any { "Kindle the lantern" in it } }
        since = bots.act(BOT, BotAction.ClickSlot(22)).since
        bots.eventually(BOT) { s -> s.menu!!.items.singleOrNull { it.slot == 13 }?.name == "Kindled Lantern" }
        bots.act(BOT, BotAction.CloseMenu)
        bots.eventually(BOT) { item("Kindled Lantern") != null }
        assertTrue("altar_tender" in probe("advancements $BOT").first(), "infusing earns Altar Tender")
        println("[vale] altar events ${bots.events(BOT, since).filterIsInstance<BotEvent.Sound>().map { it }}")
    }

    @Test
    @Order(7)
    fun `the kindled lantern raised at the shrine lifts to the sky reach and back`() {
        val kindled = item("Kindled Lantern")!!.slot
        assertTrue(kindled < 9, "the lantern came back into the hotbar: $kindled")
        bots.act(BOT, BotAction.SelectSlot(kindled))
        var since = bots.act(BOT, BotAction.UseItem()).since
        val ask = bots.heard(BOT, since, BotEvent.Dialog::class.java).dialog
        assertEquals("confirmation", ask.type)
        bots.act(BOT, BotAction.DialogButton(button = "Rise"))
        val up = bots.eventually(BOT) { it.world == "sky_reach" }
        println("[vale] up at ${up.x} ${up.y} ${up.z}")
        assertTrue(up.y > 120, "on the landing: ${up.y}")
        assertEquals(listOf("minecraft:note_block", "lumen_lamp"), probe("landing"))
        assertTrue("above_the_vale" in probe("advancements $BOT").first())
        since = bots.act(BOT, BotAction.UseItem()).since
        val down = bots.eventually(BOT) { it.world == "world" }
        println("[vale] back at ${down.x} ${down.y} ${down.z} (${bots.events(BOT, since).size} events)")
    }

    @Test
    @Order(8)
    fun `wisps appear by themselves in the grove at night`() {
        probe("time world 18000", "time")
        val appeared = waitFor(90) { probe("centities wisp")[1].toInt() > 0 }
        val wisps = probe("centities wisp")
        println("[vale] natural wisps after waiting: $wisps")
        assertTrue(appeared && wisps[4] == "true", "a natural wisp appeared near the bot: $wisps")
    }

    @Test
    @Order(9)
    fun `tortoises appear by themselves in the meadows by day`() {
        probe("time world 6000", "time")
        val meadows = probe("locate world mossy_meadows")[1].split(' ').map { it.toInt() }
        val top = probe("column world ${meadows[0]} ${meadows[2]}")[0].split(' ').map { it.toInt() }
        bots.act(BOT, BotAction.Teleport(top[0] + 0.5, top[1] + 1.0, top[2] + 0.5))
        val appeared = waitFor(90) { probe("centities moss_tortoise")[1].toInt() > 0 }
        println("[vale] tortoises: ${probe("centities moss_tortoise")}")
        assertTrue(appeared, "a moss tortoise appeared in the meadows")
    }

    @Test
    @Order(10)
    fun `no script failed along the way`() {
        val errors = editor.seen.filterIsInstance<ScriptError>()
        errors.forEach { println("[vale] script error ${it.source?.file}:${it.source?.line} ${it.message}") }
        val warnings = log.readText().lines().filter { "WARN" in it || "ERROR" in it || "Exception" in it }
        warnings.forEach { println("[vale] console: $it") }
        assertEquals(emptyList(), errors.map { "${it.source?.file}:${it.source?.line} ${it.message}" })
    }

    private companion object {
        const val BOT = "Tester"
        const val LOG = "LumenValeScenario.log"
        const val SEED = 20261007L
        val BIOMES = setOf("mossy_meadows", "crystal_grove", "ashen_ridge")
    }
}
