import { FEATURES } from '@netherforge/format/constants'
import type { ApiSpec, EventSpec, FeatureId, LuaClass } from '../../src/types.ts'

/** The feature table `since` is read against: format's, unless a test hands its own ([useFeatures]). */
let features: Record<FeatureId, { since: string }> = FEATURES

/**
 * The test hook: reads `since` against [table] until the returned function puts format's back
 * (format's table may hold nothing a test could rely on).
 */
export function useFeatures(table: Record<FeatureId, { since: string }>): () => void {
  features = table
  return () => {
    features = FEATURES
  }
}

/** The Minecraft version a feature the spec names in `since` arrived in, from format's feature table. */
export function sinceVersion(feature: FeatureId): string {
  const found = features[feature]
  if (!found) throw new Error(`"${feature}" isn't in format's feature table (game/Features.kt)`)
  return found.since
}

/** What the docs and stubs say of a function that waits (`waits` in the spec). */
export const WAITS =
  "Only in a task's own code (`nf.task`): it waits, so calling it anywhere else (an event handler, a timer, a script's body) is an error."

/** What the docs and stubs say of a saveable handle class (`saveable` in the spec). */
export const SAVEABLE =
  'A `data()` table, `Item.data` and `nf.json` can keep one: it is saved as what identifies it and comes back as a handle.'

/** The line every generated file opens with. */
export const GENERATED_BY =
  'Generated by packages/api/scripts/generate.ts from packages/api/src/spec. Edit the spec, then run `pnpm generate`.'

/** Every class that has events (`:on`), `nf` first: the classes with an `<Class>.Event` alias. */
export function eventedClasses(spec: ApiSpec): (LuaClass & { events: EventSpec[] })[] {
  return spec.classes.filter(
    (it): it is LuaClass & { events: EventSpec[] } => (it.events?.length ?? 0) > 0,
  )
}

/** The alias of a class's event names, which `on`'s `event` parameter is typed as: `Centity.Event`. */
export const eventAlias = (cls: { name: string }) => `${cls.name}.Event`
