-- The project terrain (terrain/<id>.json) a world its scripts or its netherforge.json made
-- was generated by, so the world is loaded with it again. NULL for any other.
ALTER TABLE worlds ADD COLUMN terrain TEXT;
