package dev.netherforge.format.codegen

import dev.netherforge.format.ProblemCodes
import dev.netherforge.format.biome.BiomeClimate
import dev.netherforge.format.biome.BiomeColors
import dev.netherforge.format.biome.BiomeMusic
import dev.netherforge.format.biome.BiomeSpawn
import dev.netherforge.format.biome.MoodSound
import dev.netherforge.format.centity.ResolvedPhysics
import dev.netherforge.format.centity.SpawningDef
import dev.netherforge.format.centity.TextDisplay
import dev.netherforge.format.cutscene.Cue
import dev.netherforge.format.cutscene.CutsceneFile
import dev.netherforge.format.dialog.DialogType
import dev.netherforge.format.dimensiontype.DimensionTypeColors
import dev.netherforge.format.dimensiontype.DimensionTypeFile
import dev.netherforge.format.game.FeatureTable
import dev.netherforge.format.game.GameDataBundle
import dev.netherforge.format.game.GameIds
import dev.netherforge.format.game.MinecraftVersion
import dev.netherforge.format.game.ParticleDataKind
import dev.netherforge.format.game.RegistryKey
import dev.netherforge.format.item.ItemFile
import dev.netherforge.format.json.CanonicalJson
import dev.netherforge.format.menu.MenuType
import dev.netherforge.format.noise.NoiseDef
import dev.netherforge.format.particle.EmitterDef
import dev.netherforge.format.particle.ParticleEffectFile
import dev.netherforge.format.particle.ParticleOptions
import dev.netherforge.format.project.BundleManifest
import dev.netherforge.format.project.Kinds
import dev.netherforge.format.project.Layout
import dev.netherforge.format.project.LockFile
import dev.netherforge.format.project.ModuleKind
import dev.netherforge.format.project.Names
import dev.netherforge.format.project.ProjectManifest
import dev.netherforge.format.project.Templates
import dev.netherforge.format.recipe.RecipeType
import dev.netherforge.format.recipe.RecipeValidator
import dev.netherforge.format.ref.Ref
import dev.netherforge.format.ref.RefKind
import dev.netherforge.format.resourcepack.GlyphDef
import dev.netherforge.format.resourcepack.ItemModelParent
import dev.netherforge.format.resourcepack.PackSounds
import dev.netherforge.format.resourcepack.ResourcePackFile
import dev.netherforge.format.resourcepack.SkinDef
import dev.netherforge.format.script.ScriptDef
import dev.netherforge.format.terrain.Cave
import dev.netherforge.format.terrain.Climate
import dev.netherforge.format.terrain.Floor
import dev.netherforge.format.terrain.Islands
import dev.netherforge.format.terrain.Jitter
import dev.netherforge.format.terrain.Ore
import dev.netherforge.format.terrain.Terrain
import dev.netherforge.format.terrain.TerrainFile
import dev.netherforge.format.terrain.TerrainNoise
import dev.netherforge.format.terrain.TerrainScript
import dev.netherforge.format.terrain.WorldHeight
import dev.netherforge.format.text.DefaultFontFile
import kotlinx.serialization.descriptors.StructureKind
import kotlinx.serialization.json.JsonPrimitive

/**
 * `constants.ts`: the facts about files that aren't types (defaults, limits,
 * naming rules, where each kind lives), each read from the Kotlin declaration
 * that owns it. The editor imports these instead of keeping copies.
 */
internal object Constants {
    /** Game data that tells every template what it may ask: a kind has a template when it makes one given this. */
    private val TEMPLATE_GAME = GameDataBundle(minecraft = "26.3", dataPackFormat = listOf(121, 0))

    fun render(): String = buildString {
        append("// Generated by format's generateContract task from the Kotlin model. Do not edit.\n\n")
        append(
            "import type { Billboard, DialogType, MenuType, ItemModelParent, ParticleDataKind, RecipeCategory, RecipeType, Severity } " +
                "from './types'\n\n"
        )

        append("/** Every document kind format parses and writes (`DocumentKind.id`). */\n")
        append("export const DOCUMENT_KINDS = [${Kinds.documents.joinToString(", ") { str(it.id) }}] as const\n")
        append("export type DocumentKindId = (typeof DOCUMENT_KINDS)[number]\n\n")
        kinds()
        append("export const MANIFEST_FILE = ${str(ProjectManifest.FILE_NAME)}\n")
        append("/** What a project's dependencies resolved to, beside its manifest; and the manifest at the top of a bundle. */\n")
        append("export const LOCK_FILE = ${str(LockFile.FILE_NAME)}\n")
        append("export const BUNDLE_FILE = ${str(BundleManifest.FILE_NAME)}\n")
        append("/** The file a module runs on load: `modules/<id>/init.lua`. */\n")
        append("export const MODULE_ENTRY = ${str(ModuleKind.ENTRY)}\n")
        append("/** A resource pack's pictures live in this folder inside it. */\n")
        append("export const RESOURCE_PACK_TEXTURES = ${str(ResourcePackFile.TEXTURES)}\n")
        append("/** A resource pack's sounds (`.ogg` files, each a sound event) live in this folder inside it. */\n")
        append("export const RESOURCE_PACK_SOUNDS = ${str(ResourcePackFile.SOUNDS)}\n")
        append("/** A texture's path under a resource pack's `textures/` folder (`gui/shop.png`), as `pack.json` names it. */\n")
        append("export const RESOURCE_PACK_TEXTURE_EXTENSION = ${str(ResourcePackFile.TEXTURE_EXTENSION)}\n")
        append("export const RESOURCE_PACK_TEXTURE_PATH_PATTERN = ${regex(ResourcePackFile.TEXTURE_PATH.pattern)}\n")
        append("export const RESOURCE_PACK_TEXTURE_PATH_RULE = ${str(ResourcePackFile.TEXTURE_PATH_RULE)}\n")
        append("/** Each resource pack entry kind's fields that name a texture, in declaration order. */\n")
        append("export const RESOURCE_PACK_TEXTURE_FIELDS = {\n")
        for ((kind, fields) in resourcePackTextureFields()) append("  ${key(kind)}: [${fields.joinToString(", ") { str(it) }}],\n")
        append("} as const\n")
        append("/** A sound file's path under a resource pack's `sounds/` (`menu/open.ogg`), and the key it plays as (`menu/open`). */\n")
        append("export const RESOURCE_PACK_SOUND_EXTENSION = ${str(PackSounds.EXTENSION)}\n")
        append("export const RESOURCE_PACK_SOUND_FILE_PATTERN = ${regex(PackSounds.FILE.pattern)}\n")
        append("export const RESOURCE_PACK_SOUND_KEY_PATTERN = ${regex(PackSounds.KEY.pattern)}\n")
        append("export const RESOURCE_PACK_SOUND_KEY_RULE = ${str(PackSounds.KEY_RULE)}\n")
        append("/** The default font's advances, which the editor writes from the imported client for the server to measure text. */\n")
        append("export const DEFAULT_FONT_FILE = ${str(DefaultFontFile.FILE)}\n")
        append("/** The shape of game data the editor reads (`GameDataBundle.schema`): a cached export of another is stale. */\n")
        append("export const GAME_DATA_SCHEMA = ${GameDataBundle.SCHEMA}\n")
        append("/** The oldest Minecraft version a project may target. */\n")
        append("export const OLDEST_MINECRAFT = ${str(MinecraftVersion.OLDEST_SUPPORTED)}\n")
        append(
            "/** What NetherForge uses that not every supported version has, by id: the version it arrived in, and what it is. " +
                "The Lua API's spec names these in `since`. */\n"
        )
        append("export const FEATURES: Record<string, { since: string; what: string }> = {\n")
        for (feature in FeatureTable.CURRENT.all) {
            append("  ${key(feature.id)}: { since: ${str(feature.since.toString())}, what: ${str(feature.what)} },\n")
        }
        append("}\n")
        append(
            "/** Registries the editor reads from `GameDataBundle.registries` by name: blocks (which `blocks` describes), items, loot tables, enchantments and advancement triggers. */\n"
        )
        append("export const BLOCK_REGISTRY = ${str(RegistryKey.BLOCK.id)}\n")
        append("export const ITEM_REGISTRY = ${str(RegistryKey.ITEM.id)}\n")
        append("export const LOOT_TABLE_REGISTRY = ${str(RegistryKey.LOOT_TABLE.id)}\n")
        append("export const ENCHANTMENT_REGISTRY = ${str(RegistryKey.ENCHANTMENT.id)}\n")
        append("export const TRIGGER_TYPE_REGISTRY = ${str(RegistryKey.TRIGGER_TYPE.id)}\n")
        append("/** And what a biome names: biomes themselves, entity types, sound events, particles and placed features. */\n")
        append("export const BIOME_REGISTRY = ${str(RegistryKey.BIOME.id)}\n")
        append("export const ENTITY_TYPE_REGISTRY = ${str(RegistryKey.ENTITY_TYPE.id)}\n")
        append("export const SOUND_EVENT_REGISTRY = ${str(RegistryKey.SOUND_EVENT.id)}\n")
        append("export const PARTICLE_TYPE_REGISTRY = ${str(RegistryKey.PARTICLE_TYPE.id)}\n")
        append("export const PLACED_FEATURE_REGISTRY = ${str(RegistryKey.PLACED_FEATURE.id)}\n")
        append("/** The game's own namespace, which a reference to one of the game's biomes is written in (`minecraft:plains`). */\n")
        append("export const GAME_NAMESPACE = ${str(GameIds.NAMESPACE)}\n")
        append("/** Agent instructions in a project's root, and what the editor writes for agents into .netherforge/. */\n")
        append(
            "export const AGENT_FILES = { agents: ${str(Templates.AGENTS_FILE)}, claude: ${str(Templates.CLAUDE_FILE)}, " +
                "docs: ${str(Templates.AGENT_DOCS)}, cli: ${str(Templates.CLI_FILE)}, " +
                "luals: ${str(Templates.LUALS_LIBRARY)} } as const\n\n"
        )

        append("/** A resource id: a folder name, a Lua string and a Minecraft namespace. */\n")
        append("export const ID_PATTERN = ${regex(Names.ID.pattern)}\n")
        append("export const ID_RULE = ${str(Names.ID_RULE)}\n")
        append("export const NODE_NAME_PATTERN = ${regex(Names.NODE_NAME.pattern)}\n")
        append("export const NODE_NAME_RULE = ${str(Names.NODE_NAME_RULE)}\n")
        append("/** A project's namespace, as `netherforge.json` takes it, and the ones no project may take. */\n")
        append("export const NAMESPACE_PATTERN = ${regex(Names.NAMESPACE.pattern)}\n")
        append("export const NAMESPACE_RULE = ${str(Names.NAMESPACE_RULE)}\n")
        append("export const RESERVED_NAMESPACES = [${Names.RESERVED_NAMESPACES.sorted().joinToString(", ") { str(it) }}] as const\n")
        append("/** A project's version: Semantic Versioning. */\n")
        append("export const VERSION_PATTERN = ${regex(Names.SEMVER.pattern)}\n")
        append("/** A world's name on the server, as `managedWorlds` takes it. */\n")
        append("export const WORLD_NAME_PATTERN = ${regex(Names.WORLD_NAME.pattern)}\n")
        append("export const WORLD_NAME_RULE = ${str(Names.WORLD_NAME_RULE)}\n")
        append("/** A permission node, as `allow.permissions` takes it. */\n")
        append("export const PERMISSION_NODE_PATTERN = ${regex(Names.PERMISSION_NODE.pattern)}\n")
        append("export const PERMISSION_NODE_RULE = ${str(Names.PERMISSION_NODE_RULE)}\n")
        append("/** A host `requires.http` lists, and a plugin `requires.plugins` names. */\n")
        append("export const HTTP_HOST_PATTERN = ${regex(Names.HTTP_HOST.pattern)}\n")
        append("export const HTTP_HOST_RULE = ${str(Names.HTTP_HOST_RULE)}\n")
        append("export const PLUGIN_NAME_PATTERN = ${regex(Names.PLUGIN_NAME.pattern)}\n")
        append("export const PLUGIN_NAME_RULE = ${str(Names.PLUGIN_NAME_RULE)}\n")
        append("/** One segment of a relative path inside a resource. */\n")
        append("export const PATH_SEGMENT_PATTERN = ${regex(Names.SEGMENT.pattern)}\n")
        append("/** A module's Lua file, relative to the module's folder. */\n")
        append("export const LUA_FILE_PATTERN = ${regex(Names.LUA_FILE.pattern)}\n\n")

        append("/** Each menu type's columns, and its fixed slot count (0: a chest's rows decide). */\n")
        append("export const MENU_TYPES: Record<MenuType, { columns: number; fixedSlots: number }> = {\n")
        for (type in MenuType.entries) {
            append("  ${key(CanonicalJson.serialName(type))}: { columns: ${type.columns}, fixedSlots: ${type.fixedSlots} },\n")
        }
        append("}\n")
        append("export const MENU_ROWS = { default: ${MenuType.DEFAULT_ROWS}, max: ${MenuType.MAX_ROWS} } as const\n\n")

        append("/** How many buttons each dialog type shows; null for any number. */\n")
        append("export const DIALOG_BUTTON_LIMITS: Record<DialogType, number | null> = {\n")
        for (type in DialogType.entries) append("  ${key(CanonicalJson.serialName(type))}: ${type.buttonLimit},\n")
        append("}\n")
        append(
            "export const DIALOG_COLUMNS = { min: ${DialogType.MIN_COLUMNS}, max: ${DialogType.MAX_COLUMNS}, " +
                "default: ${DialogType.DEFAULT_COLUMNS} } as const\n\n"
        )

        append("export const TEXT_DEFAULTS: { lineWidth: number; billboard: Billboard } = {\n")
        append("  lineWidth: ${TextDisplay.DEFAULT_LINE_WIDTH},\n")
        append("  billboard: ${str(CanonicalJson.serialName(TextDisplay.DEFAULT_BILLBOARD))},\n")
        append("}\n")
        append(
            "export const SKIN_DEFAULTS = { height: ${SkinDef.DEFAULT_HEIGHT}, ascent: ${SkinDef.DEFAULT_ASCENT}, " +
                "offset: ${SkinDef.DEFAULT_OFFSET} } as const\n"
        )
        append("export const GLYPH_DEFAULTS = { height: ${GlyphDef.DEFAULT_HEIGHT}, ascent: ${GlyphDef.DEFAULT_ASCENT} } as const\n")
        append("export const ITEM_MODEL_DEFAULT_PARENT: ItemModelParent = ${str(CanonicalJson.serialName(ItemModelParent.GENERATED))}\n")
        append("/** An item's fields a project item's file doesn't have: they belong to each stack, or name the item itself. */\n")
        append("export const ITEM_STACK_FIELDS = [${ItemFile.STACK_FIELDS.joinToString(", ") { str(it) }}] as const\n")
        append("/** A crafting grid's rows and columns, and the most ingredients a shapeless recipe takes. */\n")
        append(
            "export const RECIPE_GRID = { size: ${RecipeValidator.GRID}, mostIngredients: ${RecipeValidator.MOST_INGREDIENTS} } as const\n"
        )
        append(
            "/** What each recipe type takes: its ingredient and number fields, its recipe book categories, " +
                "a group, and its default cooking time (0: it doesn't cook). */\n"
        )
        append(
            "export const RECIPE_TYPES: Record<RecipeType, { required: readonly string[]; optional: readonly string[]; " +
                "categories: readonly RecipeCategory[]; group: boolean; cookingTime: number }> = {\n"
        )
        for (type in RecipeType.entries) {
            val required = type.requiredFields.joinToString(", ") { str(it) }
            val optional = type.optionalFields.joinToString(", ") { str(it) }
            val categories = type.categories.joinToString(", ") { str(CanonicalJson.serialName(it)) }
            append(
                "  ${key(CanonicalJson.serialName(type))}: { required: [$required], optional: [$optional], " +
                    "categories: [$categories], group: ${type.takesGroup}, cookingTime: ${type.defaultCookingTime} },\n"
            )
        }
        append("}\n")
        append("/** Lua instructions a script may run per call, unless its file says otherwise. */\n")
        append("export const SCRIPT_DEFAULT_BUDGET = ${ScriptDef.DEFAULT_BUDGET}\n\n")

        append("/** What an absent physics field means. */\n")
        append("export const PHYSICS_DEFAULTS = {\n")
        append("  gravity: ${num(ResolvedPhysics.DEFAULT_GRAVITY)},\n")
        append("  bounciness: ${num(ResolvedPhysics.DEFAULT_BOUNCINESS)},\n")
        append("  friction: ${num(ResolvedPhysics.DEFAULT_FRICTION)},\n")
        append("  drag: ${num(ResolvedPhysics.DEFAULT_DRAG)},\n")
        append("  angularDrag: ${num(ResolvedPhysics.DEFAULT_ANGULAR_DRAG)},\n")
        append("  maxSpeed: ${num(ResolvedPhysics.DEFAULT_MAX_SPEED)},\n")
        append("  maxSpin: ${num(ResolvedPhysics.DEFAULT_MAX_SPIN)},\n")
        append("} as const\n\n")

        append("/** What an absent `spawning` field means, and the ring around a player the spawner places centities in. */\n")
        append("export const SPAWNING_DEFAULTS = {\n")
        append("  weight: ${SpawningDef.DEFAULT_WEIGHT},\n")
        append("  cap: ${SpawningDef.DEFAULT_CAP},\n")
        append("  despawnDistance: ${SpawningDef.DEFAULT_DESPAWN_DISTANCE},\n")
        append("  minLight: ${SpawningDef.MIN_LIGHT},\n")
        append("  maxLight: ${SpawningDef.MAX_LIGHT},\n")
        append("  minDistance: ${SpawningDef.MIN_DISTANCE},\n")
        append("  maxDistance: ${SpawningDef.MAX_DISTANCE},\n")
        append("} as const\n\n")

        append("/** Cutscene limits: the validator's ranges, and what an absent cue duration means. */\n")
        append("export const CUTSCENE_LIMITS = {\n")
        append("  maxLength: ${num(CutsceneFile.MAX_LENGTH)},\n")
        append("  maxKeys: ${CutsceneFile.MAX_KEYS},\n")
        append("  maxCoordinate: ${num(CutsceneFile.MAX_COORDINATE)},\n")
        append("  defaultCueDuration: ${num(Cue.DEFAULT_DURATION)},\n")
        append("} as const\n\n")

        append("/** Terrain limits (the validator's ranges) and what an absent field means. */\n")
        append("export const TERRAIN_LIMITS = {\n")
        append("  minY: ${WorldHeight.LIMITS.minY},\n")
        append("  maxY: ${WorldHeight.LIMITS.maxY - 1},\n")
        append("  maxLayers: ${TerrainFile.MAX_LAYERS},\n")
        append("  maxNamed: ${TerrainFile.MAX_NAMED},\n")
        append("  maxNoises: ${TerrainFile.MAX_NOISES},\n")
        append("  maxThickness: ${TerrainFile.MAX_THICKNESS},\n")
        append("  maxAmplitude: ${num(TerrainFile.MAX_AMPLITUDE)},\n")
        append("  maxOreSize: ${TerrainFile.MAX_ORE_SIZE},\n")
        append("  maxOreVeins: ${TerrainFile.MAX_ORE_VEINS},\n")
        append("  maxDecorationCount: ${TerrainFile.MAX_DECORATION_COUNT},\n")
        append("  maxOn: ${TerrainFile.MAX_ON},\n")
        append("  maxBlend: ${TerrainFile.MAX_BLEND},\n")
        append("  maxScale: ${num(TerrainFile.MAX_SCALE)},\n")
        append("  minIslandsThickness: ${Islands.MIN_THICKNESS},\n")
        append("  maxOctaves: ${NoiseDef.MAX_OCTAVES},\n")
        append("  maxFrequency: ${num(NoiseDef.MAX_FREQUENCY)},\n")
        append("  minScriptBudget: ${TerrainScript.MIN_BUDGET},\n")
        append("  maxScriptBudget: ${TerrainScript.MAX_BUDGET},\n")
        append("} as const\n")
        append("export const TERRAIN_DEFAULTS = {\n")
        append("  base: ${Terrain.DEFAULT_BASE},\n")
        append("  seaLevel: ${Terrain.DEFAULT_SEA_LEVEL},\n")
        append("  fluid: ${str(TerrainFile.DEFAULT_FLUID)},\n")
        append("  stone: ${str(TerrainFile.DEFAULT_STONE)},\n")
        append("  biome: ${str(TerrainFile.DEFAULT_BIOME)},\n")
        append("  amplitude: ${num(TerrainNoise.DEFAULT_AMPLITUDE)},\n")
        append("  floorBlock: ${str(Floor.DEFAULT_BLOCK)},\n")
        append("  floorThickness: ${Floor.DEFAULT_THICKNESS},\n")
        append("  noiseFrequency: ${num(NoiseDef.DEFAULT_FREQUENCY)},\n")
        append("  noiseLacunarity: ${num(NoiseDef.DEFAULT_LACUNARITY)},\n")
        append("  noiseGain: ${num(NoiseDef.DEFAULT_GAIN)},\n")
        append("  caveMinY: ${Cave.DEFAULT_MIN_Y},\n")
        append("  caveMaxY: ${Cave.DEFAULT_MAX_Y},\n")
        append("  caveDepth: ${Cave.DEFAULT_DEPTH},\n")
        append("  caveCheese: ${num(Cave.DEFAULT_CHEESE)},\n")
        append("  caveSpaghetti: ${num(Cave.DEFAULT_SPAGHETTI)},\n")
        append("  oreSize: ${Ore.DEFAULT_SIZE},\n")
        append("  oreVeins: ${Ore.DEFAULT_VEINS},\n")
        append("  oreMinY: ${Ore.DEFAULT_MIN_Y},\n")
        append("  oreMaxY: ${Ore.DEFAULT_MAX_Y},\n")
        append("  blend: ${Terrain.DEFAULT_BLEND},\n")
        append("  jitterAmplitude: ${num(Jitter.DEFAULT_AMPLITUDE)},\n")
        append("  jitterFrequency: ${num(Jitter.DEFAULT_NOISE.frequency ?: NoiseDef.DEFAULT_FREQUENCY)},\n")
        append("  climateFrequency: ${num(Climate.DEFAULT_NOISE.frequency ?: NoiseDef.DEFAULT_FREQUENCY)},\n")
        append("  decorationCount: 1,\n")
        append("  squash: 1,\n")
        append("  islandsY: ${Islands.DEFAULT_Y},\n")
        append("  islandsThickness: ${Islands.DEFAULT_THICKNESS},\n")
        append("  islandsThreshold: ${num(Islands.DEFAULT_THRESHOLD)},\n")
        append("  islandsFrequency: ${num(Islands.DEFAULT_NOISE.frequency ?: NoiseDef.DEFAULT_FREQUENCY)},\n")
        append("  scriptBudget: ${TerrainScript.DEFAULT_BUDGET},\n")
        append("} as const\n")
        append("/** The heights of a normal overworld, what the terrain preview draws until a world says otherwise. */\n")
        append(
            "export const WORLD_HEIGHT_OVERWORLD = { minY: ${WorldHeight.OVERWORLD.minY}, maxY: ${WorldHeight.OVERWORLD.maxY} } as const\n\n"
        )

        append("/** What an absent biome field means, and the validator's ranges. */\n")
        append("export const BIOME_DEFAULTS = {\n")
        append("  temperature: ${num(BiomeClimate.DEFAULT_TEMPERATURE)},\n")
        append("  downfall: ${num(BiomeClimate.DEFAULT_DOWNFALL)},\n")
        append("  minTemperature: ${num(BiomeClimate.MIN_TEMPERATURE)},\n")
        append("  maxTemperature: ${num(BiomeClimate.MAX_TEMPERATURE)},\n")
        append("  water: ${str(BiomeColors.DEFAULT_WATER)},\n")
        append("  colorPattern: ${regex(BiomeColors.COLOR.pattern)},\n")
        append("  spawnWeight: ${BiomeSpawn.DEFAULT_WEIGHT},\n")
        append("  moodTickDelay: ${MoodSound.DEFAULT_TICK_DELAY},\n")
        append("  moodBlockSearchExtent: ${MoodSound.DEFAULT_BLOCK_SEARCH_EXTENT},\n")
        append("  moodOffset: ${num(MoodSound.DEFAULT_OFFSET)},\n")
        append("  musicMinDelay: ${BiomeMusic.DEFAULT_MIN_DELAY},\n")
        append("  musicMaxDelay: ${BiomeMusic.DEFAULT_MAX_DELAY},\n")
        append("} as const\n\n")

        append("/** What an absent dimension type field means, and the validator's ranges. */\n")
        append("export const DIMENSION_TYPE_DEFAULTS = {\n")
        append("  minY: ${DimensionTypeFile.DEFAULT_MIN_Y},\n")
        append("  height: ${DimensionTypeFile.DEFAULT_HEIGHT},\n")
        append("  lowestY: ${DimensionTypeFile.LOWEST_Y},\n")
        append("  topY: ${DimensionTypeFile.TOP_Y},\n")
        append("  section: ${DimensionTypeFile.SECTION},\n")
        append("  cloudHeight: ${num(DimensionTypeFile.DEFAULT_CLOUD_HEIGHT)},\n")
        append("  monsterLightMin: ${DimensionTypeFile.DEFAULT_MONSTER_LIGHT_MIN},\n")
        append("  monsterLightMax: ${DimensionTypeFile.DEFAULT_MONSTER_LIGHT_MAX},\n")
        append("  maxLight: ${DimensionTypeFile.MAX_LIGHT},\n")
        append("  infiniburn: ${str(DimensionTypeFile.DEFAULT_INFINIBURN)},\n")
        append("  minCoordinateScale: ${num(DimensionTypeFile.MIN_COORDINATE_SCALE)},\n")
        append("  maxCoordinateScale: ${num(DimensionTypeFile.MAX_COORDINATE_SCALE)},\n")
        append("  sky: ${str(DimensionTypeColors.DEFAULT_SKY)},\n")
        append("  fog: ${str(DimensionTypeColors.DEFAULT_FOG)},\n")
        append("  clouds: ${str(DimensionTypeColors.DEFAULT_CLOUDS)},\n")
        append("  colorPattern: ${regex(DimensionTypeColors.COLOR.pattern)},\n")
        append("  cloudColorPattern: ${regex(DimensionTypeColors.CLOUD_COLOR.pattern)},\n")
        append("} as const\n\n")

        append("/** Particle effect limits: the validator's ranges. */\n")
        append("export const PARTICLE_LIMITS = {\n")
        append("  minDuration: ${ParticleEffectFile.MIN_DURATION},\n")
        append("  maxDuration: ${ParticleEffectFile.MAX_DURATION},\n")
        append("  maxPointsPerTick: ${ParticleEffectFile.MAX_POINTS_PER_TICK},\n")
        append("  maxBurst: ${EmitterDef.MAX_BURST},\n")
        append("  maxRate: ${num(EmitterDef.MAX_RATE)},\n")
        append("  maxCount: ${EmitterDef.MAX_COUNT},\n")
        append("  minSize: ${num(EmitterDef.MIN_SIZE)},\n")
        append("  maxSize: ${num(EmitterDef.MAX_SIZE)},\n")
        append("} as const\n")
        append("/** What an absent emitter field means. */\n")
        append(
            "export const PARTICLE_DEFAULTS = { count: ${EmitterDef.DEFAULT_COUNT}, size: ${num(EmitterDef.DEFAULT_SIZE)}, " +
                "color: ${str(EmitterDef.DEFAULT_COLOR)} } as const\n"
        )
        append("/** The emitter data fields each particle data kind takes, and the one it can't go without. */\n")
        append("export const PARTICLE_OPTIONS: Record<ParticleDataKind, { takes: readonly string[]; requires: string | null }> = {\n")
        for (kind in ParticleDataKind.entries) {
            val takes = ParticleOptions.takes(kind).joinToString(", ") { str(it) }
            val requires = ParticleOptions.required(kind)?.let { str(it) } ?: "null"
            append("  ${key(CanonicalJson.serialName(kind))}: { takes: [$takes], requires: $requires },\n")
        }
        append("}\n\n")
        problemCodes()
    }

    /**
     * `KINDS`, format's registry of resource kinds ([Kinds.all], in reload
     * order) as the editor reads it, and the kind id types derived from it.
     * The editor looks kinds up here rather than listing them.
     */
    private fun StringBuilder.kinds() {
        append("/** What the editor knows of a resource kind (format's `KindSpec`). */\n")
        append("export interface KindInfo {\n")
        append("  /** The project folder its resources live in. */\n")
        append("  folder: string\n")
        append("  /** A folder per resource (`<folder>/<id>/…`), or one file (`<folder>/<id><extension>`). */\n")
        append("  layout: 'folder' | 'file'\n")
        append(
            "  /** The file that makes a folder a resource; null for a single-file kind, or a folder any file makes one (a module). */\n"
        )
        append("  main: string | null\n")
        append("  /** A single-file kind's extension. */\n")
        append("  extension: string | null\n")
        append("  /** A single-file kind's companion document, beside the file and named like it (a structure's `.json`). */\n")
        append("  companion: string | null\n")
        append(
            "  /** JSON format reads (a document kind of the same id), Lua or SQL (files only the server runs), or Minecraft's binary files only the server reads. */\n"
        )
        append("  contents: 'json' | 'lua' | 'sql' | 'binary'\n")
        append("  /** Its resources run Lua: `newScript` and `newSiblingFile` take it. */\n")
        append("  scripted: boolean\n")
        append("  /** `newResourceFiles` makes one (given game data, for a kind whose new files need it). */\n")
        append("  template: boolean\n")
        append("}\n\n")
        append("/** Every resource kind, in the order a reload batch reloads them. */\n")
        append("export const KINDS = {\n")
        for (kind in Kinds.all) {
            val layout = kind.layout
            val extension = (layout as? Layout.SingleFile)?.extension
            val companion = (layout as? Layout.SingleFile)?.companion
            append(
                "  ${key(kind.id)}: { folder: ${str(kind.folder)}, layout: ${str(if (layout is Layout.Folder) "folder" else "file")}, " +
                    "main: ${opt(
                        kind.mainFile
                    )}, extension: ${opt(extension)}, companion: ${opt(companion)}, contents: ${str(kind.contents.name.lowercase())}, " +
                    "scripted: ${kind.script != null}, template: ${kind.template("id", TEMPLATE_GAME) != null} },\n"
            )
        }
        append("} as const satisfies Record<string, KindInfo>\n")
        append("export type KindId = keyof typeof KINDS\n")
        append("/** The kinds whose resources are JSON documents: each has an editor. */\n")
        append("export type DocumentResourceKindId = { [K in KindId]: (typeof KINDS)[K]['contents'] extends 'json' ? K : never }[KindId]\n")
        append("/** The kinds whose files are Minecraft's own: never read as text. */\n")
        append("export type BinaryKindId = { [K in KindId]: (typeof KINDS)[K]['contents'] extends 'binary' ? K : never }[KindId]\n")
        append("/** The kinds whose resources run Lua. */\n")
        append("export type ScriptedKindId = { [K in KindId]: (typeof KINDS)[K]['scripted'] extends true ? K : never }[KindId]\n")
        append("/** The kinds `newResourceFiles` makes. */\n")
        append("export type TemplateKindId = { [K in KindId]: (typeof KINDS)[K]['template'] extends true ? K : never }[KindId]\n\n")
    }

    /** `PROBLEM_CODES`, format's catalogue of problems ([ProblemCodes]): what a `Problem.code` can be. */
    private fun StringBuilder.problemCodes() {
        append(
            "/** Every problem code (format's `ProblemCodes`): its severity, and its entry in the docs (`docs/format/problems.md`). */\n"
        )
        append("export const PROBLEM_CODES = {\n")
        for (code in ProblemCodes.all) {
            val severity = str(CanonicalJson.serialName(code.severity))
            append("  ${str(code.code)}: { severity: $severity, docs: ${str("format/problems#${code.anchor}")} },\n")
        }
        append("} as const satisfies Record<string, { severity: Severity; docs: string }>\n")
        append("export type ProblemCode = keyof typeof PROBLEM_CODES\n")
    }

    private fun opt(text: String?) = text?.let(::str) ?: "null"

    /** `ResourcePackFile`'s keyed entry kinds (`skins`, …) and each one's fields marked `@Ref(RefKind.TEXTURE)`. */
    private fun resourcePackTextureFields(): List<Pair<String, List<String>>> {
        val pack = ResourcePackFile.serializer().descriptor
        return (0 until pack.elementsCount).mapNotNull { i ->
            val element = pack.getElementDescriptor(i)
            if (element.kind != StructureKind.MAP) return@mapNotNull null
            val entry = element.getElementDescriptor(1)
            val fields = (0 until entry.elementsCount).filter { j ->
                entry.getElementAnnotations(j).any { it is Ref && it.kind == RefKind.TEXTURE }
            }.map(entry::getElementName)
            if (fields.isEmpty()) null else pack.getElementName(i) to fields
        }
    }

    private fun str(text: String) = JsonPrimitive(text).toString()

    private fun num(value: Double) = CanonicalJson.formatNumber(value.toString())

    private fun key(name: String) = if (Regex("^[A-Za-z_][A-Za-z0-9_]*$").matches(name)) name else str(name)

    /** A JS regex literal for a Kotlin pattern (both use the same syntax for everything format writes). */
    private fun regex(pattern: String) = "/" + pattern.replace("/", "\\/") + "/"
}
