package dev.netherforge.plugin.world

import dev.netherforge.format.Problem
import dev.netherforge.format.ProblemCodes
import dev.netherforge.format.block.BlockCarriers
import dev.netherforge.format.json.CanonicalJson
import dev.netherforge.format.project.BlockKind
import dev.netherforge.format.project.ProjectManifest
import dev.netherforge.format.project.ProjectSnapshot
import dev.netherforge.format.project.TerrainKind
import dev.netherforge.format.terrain.TerrainScriptFailure
import dev.netherforge.plugin.RuntimeLog
import dev.netherforge.plugin.platform.Platform
import dev.netherforge.plugin.project.ProjectFiles
import java.util.concurrent.ConcurrentHashMap

/**
 * The project's generators for the worlds the server loads itself as it
 * starts: its main world. The server asks which generator a world has before
 * it loads it (`bukkit.yml`'s `worlds.<name>.generator: NetherForge`, which
 * the adapter answers with [generatorFor]), long before a session exists, and
 * never again until it restarts; `netherforge.json`'s
 * `worlds.<name>.generator` says which.
 *
 * So, like the start-up datapack's check, this lives as long as the plugin:
 * it remembers what the server was told, and [check] compares it with what
 * the manifest says now. Which generator the main world has changes only with
 * a restart; what that generator makes changes with every save of its file,
 * as for any world (the session publishes it again).
 */
class StartupGenerators(private val platform: Platform, private val source: ProjectFiles, private val log: RuntimeLog) {
    /** Each world the server asked about as it started, and the generator it was given (null: none). */
    private val asked = LinkedHashMap<String, String?>()

    /** Whether the main world's generator isn't the one the manifest names, which a restart changes. */
    var stale: Boolean = false
        private set

    private var problems: List<Problem> = emptyList()

    /**
     * The server is about to load world [world] and asks which of the
     * project's generators makes it: the one `netherforge.json` names for it
     * (its id as published), or null for none. The project's generators are
     * published here, before any session, so the world's first chunks and its
     * spawn are already the generator's.
     */
    fun generatorFor(world: String): String? {
        val load = source.load(platform.game)
        val snapshot = load.snapshot
        val files = load.files
        val reference = snapshot.manifest?.worlds?.get(world)?.terrain?.text
        val id = reference?.let { WorldGenerators.generatorId(snapshot, it) }?.takeIf { it in snapshot.everywhere(TerrainKind) }
        asked[world] = id
        if (id == null) {
            log.warn(
                if (reference == null) {
                    "The server asks NetherForge to generate world \"$world\", but netherforge.json names no terrain for it, so the " +
                        "server generates it itself"
                } else {
                    "netherforge.json's terrain \"$reference\" for world \"$world\" isn't a terrain of the project, so the " +
                        "server generates it itself"
                }
            )
            return null
        }
        val blocks = snapshot.everywhere(BlockKind).mapValues { it.value.compiled }
        val plan = if (blocks.isEmpty()) null else BlockCarriers.plan(blocks, snapshot.namespace, platform.game)
        val generators = WorldGenerators.resolveGenerators(
            snapshot.running(TerrainKind),
            snapshot.namespace,
            WorldGenerators.runningBiomes(snapshot),
            { plan?.stateOf(it)?.toString() },
            { name -> WorldGenerators.structureFile(snapshot, name, source::resolve)?.let(platform.structures::template) },
            { at, terrain -> WorldGenerators.scriptsFor(at, terrain, files, source::read, scriptFailed(at)) }
        ) { at, message ->
            log.warn("terrain $at: $message")
        }
        platform.worldManager.publishGenerators(generators)
        if (id !in generators) log.warn("Terrain \"$id\" has errors: world \"$world\" generates nothing until it's fixed")
        log.info("World \"$world\" is generated by the project's generator \"$id\"")
        return id
    }

    /**
     * What a generator's script fails at before any session (the spawn chunks the server makes as it starts), said
     * once each from whichever chunk thread hears it; the session publishes the generators again, and its
     * [WorldGenerators] says what they fail at from then on, problems included.
     */
    private fun scriptFailed(id: String): (TerrainScriptFailure) -> Unit {
        val said = ConcurrentHashMap.newKeySet<String>()
        return { failure ->
            if (said.size < TerrainScriptFailures.MAX_PER_GENERATOR && said.add("${failure.stage}\n${failure.message}")) {
                log.warn("terrain $id: the script's ${failure.stage} failed, so the file's own result stands there: ${failure.message}")
            }
        }
    }

    /**
     * Whether the server's main world has the generator [snapshot]'s manifest
     * names for it; when not, a restart is what changes it (a warning, once).
     * A seed for the main world is the server's own (`level-seed`), never the
     * manifest's.
     */
    fun check(snapshot: ProjectSnapshot): Boolean {
        val main = platform.worlds.defaultWorld()
        val config = snapshot.manifest?.worlds?.get(main)
        val reference = config?.terrain?.text
        // Compared by name: deleting the file isn't a change of generator (a reference to none is `reference.terrain` already).
        val wanted = reference?.let { WorldGenerators.generatorId(snapshot, it) ?: it }
        val started = asked[main]
        val path = CanonicalJson.childPath("$.worlds", main)
        val found = mutableListOf<Problem>()
        val was = stale
        // A restart changes nothing for a generator that isn't there now and wasn't then.
        stale = wanted != started && (wanted in snapshot.everywhere(TerrainKind) || started != null)
        when {
            !stale && main in asked && reference == null -> found += ProblemCodes.RUNTIME_TERRAIN.at(
                ProjectManifest.FILE_NAME,
                "bukkit.yml asks NetherForge to generate the main world \"$main\", but netherforge.json names no terrain for it: " +
                    "the server generates it itself",
                path
            )
            !stale -> {}
            main !in asked -> found += restart(
                "netherforge.json names terrain \"$wanted\" for the main world \"$main\", but the server doesn't ask NetherForge to " +
                    "generate it: add `generator: NetherForge` under `worlds.$main` in bukkit.yml and restart the server (the editor's " +
                    "dev server does this itself)",
                CanonicalJson.childPath(path, "terrain"),
                was
            )
            else -> found += restart(
                "The main world \"$main\" started with ${started?.let {
                    "generator \"$it\""
                } ?: "no generator"} and netherforge.json now " +
                    "names ${wanted?.let { "\"$it\"" } ?: "none"}: it generates as it started until the server restarts",
                if (wanted == null) path else CanonicalJson.childPath(path, "terrain"),
                was
            )
        }
        if (config?.seed != null) {
            found += ProblemCodes.RUNTIME_TERRAIN.at(
                ProjectManifest.FILE_NAME,
                "\"$main\" is the server's main world, whose seed is the server's (`level-seed` in server.properties): this one is ignored",
                CanonicalJson.childPath(path, "seed")
            )
        }
        problems = found
        return stale
    }

    /** What [check] found: `runtime.restart` while the main world's generator is out of date, `runtime.terrain` for the rest. */
    fun problems(): List<Problem> = problems

    private fun restart(message: String, at: String, was: Boolean): Problem {
        if (!was) log.warn(message)
        return ProblemCodes.RUNTIME_RESTART.at(ProjectManifest.FILE_NAME, message, at)
    }
}
