package dev.netherforge.plugin.world

import dev.netherforge.format.project.CentityKind
import dev.netherforge.format.ref.ResourceRef
import dev.netherforge.plugin.RuntimeLog
import dev.netherforge.plugin.centity.Centities
import dev.netherforge.plugin.platform.Platform
import dev.netherforge.plugin.platform.StructureMarker
import dev.netherforge.plugin.session.ReloadBatch
import dev.netherforge.plugin.session.RuntimeService

/**
 * Centities in structures. A structure's template holds `marker` entities
 * tagged `nf.centity.<centity>` (a tag is part of an entity's saved data, so
 * the template keeps it and the game places the marker where the template
 * says, rotated and mirrored with the structure, however the structure came
 * into the world: generated by the world, placed by `world:place_structure`
 * or a structure block). This turns each marker into the centity it names,
 * on the main thread, once the marker is in the world.
 *
 * Once only: the marker is taken out of the world first and the centity put
 * where it stood, so a chunk that loads again (a restart, a reload, walking
 * away and back) has no marker left to spawn from. A marker naming a
 * centity the project doesn't have (yet) stays, and is looked at again when
 * the centities reload. A marker whose chunk is unloaded isn't reached, and
 * comes again when its chunk does.
 *
 * Structure-generated spawns are this service's; natural spawning
 * (`centity.json`'s `spawning`) is the spawner's.
 */
internal class StructureSpawns(
    private val platform: Platform,
    private val centities: () -> Centities,
    private val log: RuntimeLog,
    /** The project's namespace, which a marker's own-project name is written without. */
    private val home: () -> String
) : RuntimeService {
    override val name get() = "structure spawns"

    /** A marker's centity may have been added or changed: look at every marker still waiting. */
    override val follows: Set<String> get() = setOf(CentityKind.id)

    override fun followed(kind: String, ids: Set<String>, batch: ReloadBatch) = scan()

    override fun start() = scan()

    override fun structureMarkers(markers: List<StructureMarker>) = spawn(markers)

    /** Spawns from every marker in the loaded world: after a reload, and after a script placed a structure with its entities. */
    fun scan() = spawn(platform.entities.structureMarkers())

    /** The centities already complained about, so a marker that stays doesn't say it again on every reload. */
    private val warned = HashSet<String>()

    private fun spawn(markers: List<StructureMarker>) {
        for (marker in markers) {
            val centity = ResourceRef(marker.centity).nameIn(home())
            if (centity == null || centities().definition(centity) == null) {
                if (warned.add(marker.centity)) {
                    log.warn(
                        "A structure has a marker for the centity \"${marker.centity}\", which the project doesn't have: " +
                            "the marker stays in the world, and spawns it once it does"
                    )
                }
                continue
            }
            // The marker goes first: if it can't be reached it isn't spawned from twice, only later.
            if (!platform.entities.remove(marker.id)) continue
            warned.remove(marker.centity)
            if (centities().spawn(centity, marker.at, marker.at.yaw) == null) {
                log.warn("The centity \"${marker.centity}\" couldn't be spawned from the structure marker at ${where(marker)}")
            }
        }
    }

    private fun where(marker: StructureMarker): String = with(marker.at) { "$world ${x.toInt()} ${y.toInt()} ${z.toInt()}" }
}
